apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::526934276965:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1CS50ZXPFPNCJ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::526934276965:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-22T10:44:40Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1663"
  uid: d44df60e-4d7a-443f-a815-50ae37b26bf1
